abstract final class AppRoutes {
  static const dashboard = '/';
  static const more = '/more';
  static const areas = '/areas';
  static const plantings = '/plantings';
  static const harvests = '/harvests';
  static const management = '/management';
  static const results = '/results';
  static const woodworking = '/woodworking';
  static const categories = '/categories';
  static const products = '/products';
  static const production = '/production';
  static const stock = '/stock';
  static const sales = '/sales';
  static const expenses = '/expenses';
  static const customers = '/customers';
  static const orders = '/orders';
  static const reports = '/reports';
  static const settings = '/settings';
}
